name: Compilar Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Windows

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Compilar
        run: |
          pyinstaller --onefile --name "Conversor-WEBP" --add-data "libwebp;libwebp" main.py

      - name: Subir ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: Conversor-WEBP
          path: Windows/dist/Conversor-WEBP.exe
